### PR TITLE
adding Dockerfile and instructions for use in docs/containers.md

### LINKED ISSUE #79: Docker container?
hey opendrift! I was wondering if anyone has need / desire for a Docker container? I'm a software engineer at Stanford and one of our users could use it... I'm working on one and could do a PR, and wanted to bring it up for discussion here in case there are "best practices" for the install. So far I'm using the miniconda (python 2) image from continuumio, and installing the dependencies with conda. I'm going through the errors from testing now - the first was that basemap "Axes" was missing a function, and I resolved that by doing the suggestion here: https://github.com/matplotlib/basemap/issues/395#issuecomment-381407388

I still see an issue about a missing GDAL although I've installed gdal-bin and libgeos-dev. Here is the message

```bash
DEBUG: Rasterized size: [458, 1518]
DEBUG: backend agg version v2.2
DEBUG: Calculation SRS set to: None
INFO: OpenDriftSimulation initialised (version 1.0.3)
GDAL is not available:
libgeos-3.4.2.so: cannot open shared object file: No such file or directory
```
The issue I'm having now is:

```bash
======================================================================
FAIL: test_plot_animation (test_run.TestRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/opendrift/tests/test_run.py", line 645, in test_plot_animation
    assert os.path.exists('test_plot.mp4')
AssertionError

----------------------------------------------------------------------
Ran 74 tests in 68.225s

FAILED (failures=1, skipped=5)
```
I see that the png output successfully, but the animation (mp4) did not, and I'm guessing it might be related to a library or graphics in the container? Would you be able to help me parse through these last issues and then I could contribute the Dockerfile to the repo as a PR? Many thanks!

### PR DESCRIPTION
**Pull request by vsoch**
hey OpenDrift! I've finished a Docker container, along with instructions for export to Singularity (likely the more needed one for use on a shared resource) and would like to propose adding the Dockerfile and markdown document (instructions for usage, see files section in this PR for both) to the repository. I've built the container and [provided it on Docker Hub](https://hub.docker.com/r/vanessa/opendrift/), and would be happy to update when new versions are available, or help you to build it automatically on Docker Hub from the repository. Our user at Stanford reports that the Singularity container is running smoothly for her, so I am hopeful this might be useful to others.

## Issues Addressed

- this will close #79

### CODE REVIEW

**Comment by vsoch** [comment]
Is there any reason tests would fail? I didn't actually change any code :P Should this PR be to the develop branch?

**Comment by vsoch** [comment]
Errors for "no module named conda.cli" seem to be related to setting of PYTHONPATH? See this post --> https://stackoverflow.com/questions/44784644/conda-importerror-no-module-named-conda-cli?rq=1

**Comment by vsoch** [comment]
I've just updated the PR by doing the following:

 - there are now two Dockerfiles - the first builds opendrift 1.0.4, the second is the same, but with the added NOAA oillibrary. Both I've built and am pushing versions to Docker Hub (still in progress!)
 - the Dockerfiles are organized in a subfolder docker, with a README.md instead of the previous docs/containers.md
 - I've updated the primary README.md to reflect this

I'll post links here when the containers are done being pushed! I'm happy to provide / manage these, but I can also suggest that we could build directly from this repository (on successful merge, you can deploy to Docker Hub).

**Comment by vsoch** [comment]
oup, I don't think I updated with your fixed code, one second!

**Comment by vsoch** [comment]
- [opendrift-oil](https://hub.docker.com/r/vanessa/opendrift-oil/) is ready, still building opendrift.

**Comment by vsoch** [comment]
Some of these are failing because of this:

```bash
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
```
and I literally just had this same error, for builds that were working before! The fix that I'm trying (it worked for my container, at least) is to add:

```bash
  - conda update openssl ca-certificates certifi
```
others are failing just due to network connectivity.

If this continues to be annoying, it might be worth one of the two options:
 - doing all testing, etc. in a container (so the testing environment is actually stable)
 - moving to build --> test --> deploy on circleci (I've had better luck than with travis, at least recently, the two seem to switch off).

This is probably (mostly) an issue with conda.

**Comment by vsoch** [comment]
If this install routine is not consistent, it's not good for tests. I would suggest that one of the above approaches is taken, because it's very hard to contribute when the base tests (with the code unchanged) can be run once, and then don't work the second time. Thoughts?

**Comment by vsoch** [comment]
?

**Comment by knutfrode** [comment]
Seems like this happened:
https://github.com/hpi-swa/smalltalkCI/issues/84

**Comment by vsoch** [comment]
ah ok, great to have it added! Please bother me if any work / questions arise around it.

**Comment by knutfrode** [comment]
Hi @vsoch!
Are these dockerfiles of OpenDrift still used/produced/maintained?
The present version of OpenDrift is 1.0.7, and your last dockerfile seems to cover 1.0.4.
Thus the dockerfiles are now a bit outdated. 
If there are no plans to update this, I would like to remove the link to these from the OpenDrift wiki front page.

Note that OpenDrift does now contain some conda environment files for easier installation. That might perhaps also help for making the dockerfiles(?)

**Comment by vsoch** [comment]
I’d be happy to update them! I’m not a maintainer here so I can do it by request. It’s useful for users that want to pull onto HPC as a Singularity container. When I added the recipe I also offered to help set up a build from this repo on CI, that is still an option too. I certainly would not remove- it’s important to provide reproducible deployment options.

**Comment by knutfrode** [comment]
Yes, automatic production sounds like the best option!
I have never used or produced dockerfiles myself, so have little idea how that works. Would you be able to set that up, if I granted you some permission?
OpenDrift is already checkd by Travis: https://travis-ci.org/OpenDrift/opendrift
As you see, OpenDrift is now also Python3-compliant. And the conda environment files exist for both Python2 and Python3, where for Python2 there is one with, and one without the oil library (which is unfortunately not yet Python3 compliant).

**Comment by vsoch** [comment]
I would suggest we set up a circle ci build of the Dockerfile, where it will (test build) on any branch that isn't master, and deploy on push to master. It would be best if opendrift had a docker account to push to (e.g., opendrift/opendrift) and I'll build containers for each of python 2 and 3, tagged with the python version and opendrift version. If there is a "best version" (python 3?) we can push that as a latest. To get this to work, a maintainer here will need to connect to CirceCI, and add a DOCKER_LOGIN and DOCKER_PASSWORD to the encrypted envars for the project. Then the project needs to be added to circle, and the Docker Hub account created. I can handle the rest via a PR! :_)

**Comment by knutfrode** [comment]
Ok, that sounds good.
So what exactly would I need to do? Create a docker account somewhere?
Please excuse my ignorance on this topic!

**Comment by vsoch** [comment]
No worries! Yes let me give a few steps here.

 1. the Docker account is created on Docker Hub --> https://hub.docker.com You don't need to  create any collections in advance, when the PR is merged and the push happens if the collections aren't created they will be. However, it would be good if you created opendrift/opendrirft (or whatever you choose to call it) and then minimally add some description and links back to this repo. The Docker interface is... not so great - to add a repo you should click on "repositories" in the top right, then 'create repository" and then just fill in the information (it's *not* going to be a connection to GitHub). Then you can click "Manage Repository" and look to the bottom to see the description box.

 2. The CircleCI account is created at https://circleci.com/dashboard and you have to add your org, and then the project. When you are logged in, click on your user icon in the top right, then "User Settings" and then the first screen you will see is "Account Integrations" with a link to the GitHub page where you can connect accounts. Click that and enable the OpenDrift org. It will take a few refreshes then of the circle page until you can click the top left and select OpenDrift, and then you want to "Add Project." Under Environment Variables you need to add `DOCKER_LOGIN` and `DOCKER_PASSWORD` and under Advanced Settings be sure that pipelines are turned on, Free for open source is on, build forked pull requests is on, and cancel redundant builds. Do *not* turn on passing secrets to forked pull requests.

At that point, when I open a PR it will detect the .circleci/config.yml and trigger testing. If I can't see the stuff running you might need to add me somewhere so I can debug, we can figure that out when we get there!

**Comment by knutfrode** [comment]
I think step 1. is ok. For step 2. I believe I did the necessary steps, though with slightly different route.
I added and commited a config.yml-file, but this has to be adjusted somehow:
https://github.com/OpenDrift/opendrift/commit/fbb09964de8a32126a9585144c59c79e85efc177

**Comment by knutfrode** [comment]
So now the code will be check both by Travis and CircleCI? But only CircleCI can be linked to Docker?

**Comment by vsoch** [comment]
Yeah we are basically allocated the container builds to circle, and the rest of testing to travis. I'll set it up so the container builds on a PR (to test that it does correctly) but the deployment will only happen on merge to master.

How is releasing / versioning handled? We would want the tag to correspond to that. Also, what is the Docker organization you made for opendrift - did you get opendrift?

**Comment by vsoch** [comment]
Found the docker repo! https://hub.docker.com/r/opendrift/opendrift Great work, super speedy! I'm working on the recipes now. Stay tuned!

**Comment by vsoch** [comment]
Also just found the version source:

```
cat opendrift/version.py 
__version__ = "1.0.7"
```

**Comment by vsoch** [comment]
Question - is this a conda install file for python 3 including the NOAA ADIOS oil library? Or does the oil library not have Python 3 support?

**Comment by vsoch** [comment]
And a quick question - when I originally built the containers, I found I needed basemap and openssl:

```
RUN /opt/conda/bin/conda update openssl ca-certificates certifi
RUN /opt/conda/bin/conda install --yes hdf4 numpy scipy matplotlib basemap \
                                       netcdf4 configobj pillow gdal pyproj ffmpeg

# We need basemap 1.1.0
RUN /opt/conda/bin/conda install --yes --channel conda-forge basemap basemap-data-hires
```
But I don't see this in the conda recipes. Is this changed from before? Or I'm thinking it was just a requirement for the container?

**Comment by vsoch** [comment]
Just kidding - just tested the install and they are all added with the conda config! Apologies for asking too early :)

**Comment by knutfrode** [comment]
Sounds all good so far. Yes, Oil library does not have Python3 support.

**Comment by vsoch** [comment]
@knutfrode have you set up CircleCI and enabled all the settings? The build didn't trigger on Circle here https://github.com/OpenDrift/opendrift/pull/110, and likely it's because of one of the following:

 - under project settings "Build Forked Pull Requests" must be on
 - under project settings "Build only pull requests" should be off

Take a look over the settings and let me know if you want to discuss anything. The build should be triggering on there by way of having the .circleci/config.yml, unless it doesn't know to build pull requests.

**Pull request merged**
