### PR TITLE
vertical_mixing: fix for depths below -255m

### PR DESCRIPTION
**Pull request by manuelaghito**
(no performance difference on example_mixed_layer_depth for 7 days simulation. Not tested eventual performance difference for 100000 particles yet)

### CODE REVIEW

**Comment by knutfrode** [comment]
Ready to merge?

**Comment by manuelaghito** [comment]
I was thinking to add another small thing

**Comment by manuelaghito** [comment]
well, just merge yes, I can make a new PR, it is not directly related to this

**Comment by manuelaghito** [comment]
but I have not tested with 1M particles... it was too slow

**Pull request merged**
