### PR TITLE
Adding Docker Builds and Deploy with CircleCI

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will update the CircleCI recipe to build containers for all of:

 - opendrift/opendrift   (python 3 without oil)
 - opendrift/opendrift:py2 (python 2 without oil)
 - opendrift/opendrift-oil (python 2 with oil)

Specifically, containers will be built (for preview and that the build is successful) on any PRs, and then merge to master will build and deploy the same.

There's an entire namespace that includes python 2 / python 3, along with version, and these are printed in the CI and listed in the docker/README.md. I didn't get a chance to build these all locally because it would take a looong time (conda!) but thankfully we can use the parallel Circle workflow setup to run builds at the same time. This might need some tweaking, so I'm labeling as a WIP.

I renamed the Dockerfile.oil to Dockerfile.oil.py2 in anticipation that some day we will have a Python 3 too :) 

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
See comment here -> https://github.com/OpenDrift/opendrift/pull/80#issuecomment-493124981 the build isn't triggering on Circle likely because not set up entirely!

**Comment by vsoch** [comment]
Woohoo we're running! I'll watch the builds and push updates as needed. Thanks to whomever fixed up the circle connection <3

**Comment by vsoch** [comment]
okay, first issue is with activating conda in Dockerfiles (you can't :) ) I'm testing some things locally and I'll push when I get something to work.

**Comment by vsoch** [comment]
And a little lovely note from anaconda, he's not happy that the recipes don't include pip, ha.

> Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

**Comment by vsoch** [comment]
okay, some progress! One of the container builds is good to go, the one with python 3. Here is a preview for the containers that will be tagged (and pushed):

**Comment by vsoch** [comment]
The issue for the Python 2 derivatives isn't building the main container, but running `./testall` - for some reason Python 3 doesn't bloop out without display, but python 2* versions end with:

```
TclError: no display name and no $DISPLAY environment variable
```
I tried exporting a DISPLAY to the environment, and worst case (if running ./testall requires a bind to the user display) we can skip running this command.

**Comment by vsoch** [comment]
okay, I've disabled the script running that requires display. It could be that it's a simple of customizing the test script, however that is outside of the scope of this PR. If/when it gets fixed up, we can run the tests here.

**Comment by vsoch** [comment]
Python 2 tags, without out:

image

Python 2, with oil deploys to a different container `opendrift/opendrif-oil`

image

**Comment by vsoch** [comment]
When this is merged, the push to Docker Hub will rely on the presence of the `DOCKER_LOGIN` and `DOCKER_PASSWORD` in the project environment. If those are good to go (barring any silly mistakes on my part) the containers should deploy! If I missed something, it's a quick fix to PR again with the fix.

**Comment by vsoch** [comment]
Ready for review.

**Comment by vsoch** [comment]
Worked without a hitch!

https://hub.docker.com/r/opendrift/opendrift/tags
https://hub.docker.com/r/opendrift/opendrift-oil

**Comment by knutfrode** [comment]
Does this mean that everything now works automatically?
Then thanks a lot Vanessa, for your kind contributions to mankind!

**Comment by vsoch** [comment]
Yes, pull requests will just do a test build and show the tags to be released, and merge to master will build and deploy based on python and software version. Glad to help!

**Pull request merged**
