### PR TITLE
ROMS native intake reader

### PR DESCRIPTION
**Pull request by rsignell**
This is an attempt to add an Intake reader for ROMS, as raised in #1187.   It's not working yet. 

I have a [test notebook](https://nbviewer.org/gist/rsignell-usgs/8cd9e4d0fabd3cc8c508a400a3d11324) but it's bombing out on calculating the depths. 

The OpenDrift community might find the example dataset we are using interesting/useful:

* curvilinear ROMS grid for East Coast and Gulf Coast of US
* pulls data via Intake (using zarr library and kerchunk json file) to read from a collection of NetCDF3-64-bit offset files on S3-compatible object storage
* no `open_mfdatset` required
* no credentials are required!

``` python
import intake   
intake_catalog = 'https://mghp.osn.xsede.org/rsignellbucket1/rsignell/testing/cnaps.yml'
cat = intake.open_catalog(intake_catalog)
dataset = 'CNAPS_opendrift'
ds = cat[dataset].to_dask()  # creates Xarray dataset
```
to execute the above code you need `intake-xarray`, `zarr` and `s3fs` in your environment

### CODE REVIEW

**Comment by rsignell** [comment]
@gauteh any chance you could take a quick look here? 
Does this part of the error with `Index is out of bounds for axis 0 with size 57` give any clues? 
There are 57 time steps in this test case...
``` 
12:25:33 INFO    opendrift.models.basemodel:1816: Duration, steps or end time not specified, running until end of first reader: 2023-11-03 00:00:00
12:25:33 INFO    opendrift.models.basemodel:891: Using existing reader for land_binary_mask
12:25:34 INFO    opendrift.models.basemodel:903: All points are in ocean
12:25:34 INFO    opendrift.models.basemodel.environment:670: ========================
12:25:34 ERROR   opendrift.models.basemodel.environment:671: Index is out of bounds for axis 0 with size 57
Traceback (most recent call last):
  File "/home/conda/global/e1003848400f1afa7580bb6fa3874f48f20b3522458965117a29babee3516098-20231112-153522-163623-16-opendrift/lib/python3.11/site-packages/opendrift/models/basemodel/environment.py", line 646, in get_environment
    reader.get_variables_interpolated(
  File "/home/conda/global/e1003848400f1afa7580bb6fa3874f48f20b3522458965117a29babee3516098-20231112-153522-163623-16-opendrift/lib/python3.11/site-packages/opendrift/readers/basereader/variables.py", line 889, in get_variables_interpolated
    env, env_profiles = self.get_variables_interpolated_xy(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jbzambon** [comment]
+1 for this!

**Comment by knutfrode** [comment]
I am not familiar with Intake, but 57 must be the length of the time dimension. So perhaps some dimensions got swapped somewhere?
Line 646, in `environment.py` indicates that lon/lat arrays have length equal to the time dimension (57) instead of the number of particles.
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel/environment.py#L646

**Comment by rsignell** [comment]
Finally bit the bullet and learned how to use the debugging capabilities of VS Code to figure out what was going on here.   Turns out that there was nothing wrong with the PR.   The problem was with the Kerchunked dataset we were using to test it!   When you use Kerchunk  to aggregate along the time dimension, you need to supply an `identical_dims=[]` argument that specifies the variables you *don't* want to be aggregated along the time dimension.   And `Vtransform` was missing from that list.    So it had a time dimension and 57 values instead of 1.   Once that was fixed, the example `example_roms_intake.py` script works just fine! 
opendrift_intake

**Comment by rsignell** [comment]
@knutfrode this is working and doesn't impact anything else in opendrift.    Please let me know what additional things I need to do -- I'd love to see this merged!

**Comment by gauteh** [comment]
Hi, thank you for the pull request. We are not familiar with intake, but it seems like this could be useful for many? 

In general we prefer to use the `generic` reader as it is the most general and updated one. If this needs to be specific to ROMS it is better to subclass the existing ROMS reader to avoid duplication. One approach we have used with the generic reader is to allow xarray.Dataset's to be passed in, then you can set it up in advance using intake and the reader does not need to know about intake at all.

We are also very careful about adding dependencies. It looks like some of those are for cloud based reading, which I think is something that might happen anyway. Please reduce the additional dependencies to the absolute minimum.

If we can change the reader to take an xarray object, without adding dependencies I think that would be the best option. Is that possible?

**Comment by gauteh** [comment]
That sounds great!

**Comment by rsignell** [comment]
@gauteh yes that's a much better solution!

**Comment by knutfrode** [comment]
This can be done the same way for the ROMS reader as for the generic netCDF Reader:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_netCDF_CF_generic.py#L72

You are welcome to implement this and test on your own data, and then make a pull request after it works.

**Comment by rsignell** [comment]
closing in favor of #1214

**Pull request closed without merging**
