### PR TITLE
Updates to ROMS zeta, seafloor checks, tests

### PR DESCRIPTION
**Pull request by kthyng**
* added sea_surface_height to OceanDrift and models that subclass OceanDrift, also a new parameter
* interact_with_seafloor accounts for zeta in bottom check, as does other bottom check in OceanDrift
* angle and zeta are updated in ROMS reader
* z_rho calculation is shifted so that it is 0 at the surface like z 
* tests are updated, including a ROMS reader specific test file
* changed sea_floor_depth_below_sea_level to -20 from -10 for wet/dry cases that are a little more extreme

### CODE REVIEW

**Comment by knutfrode** [comment]
Really a great job, thank you very much!
All tests are passing, and your code changes and additions look all good to me.

So I can merge this, if you think it is ready to go?

**Comment by kthyng** [comment]
@knutfrode Thank you! I was stuck for awhile thinking between z_rho and z but when I realized I could just convert from z_rho to z with zeta without something more complicated I was trying, it all worked out ok.

I am feeling pretty good about it all at this point and I think it is ready to go. I think this closes https://github.com/OpenDrift/opendrift/issues/1196 (along with https://github.com/OpenDrift/opendrift/issues/1235) also unless I realize another thing I haven't noticed 😆

**Comment by knutfrode** [comment]
Yes, we can make a new release within a few days.

**Comment by knutfrode** [comment]
Release 1.11.2 is now out. I added some release notes here:
https://opendrift.github.io/history_link.html

Feel free to suggest other formulations for your contributions, e.g. by editing history.rst directly in your browser:
https://github.com/OpenDrift/opendrift/blob/master/history.rst

It should be available on conda-forge within a couple of hours:
https://anaconda.org/conda-forge/opendrift

**Pull request merged**
