### PR TITLE
add sealice model

### PR DESCRIPTION
**Pull request by gauteh**
2021-06-21 5d629b2b julien introduced vertical mixing
2021-06-18 0160dcbf julien Debugging reader selafin the lice are now able to sense and move vertically There is a memory leak
2021-06-18 84afb9a7 julien Functional superindividuals actively swimming towards light and sinking at night
2021-06-17 f4f2a82e julien first successful loading no run yet
2021-06-16 260911ce julien Modification of variables in sea lice model minor other fiel editions
2021-06-16 4b1b1a66 julien New method for parametrisation Not working
2021-06-16 199dc25b julien use of add_config to setup the parameters Use the biomass in elements and compute the population based on proportions of the reference population (linear relation)
2021-06-16 266abf90 julien first try

### CODE REVIEW

**Comment by gauteh** [comment]
> > Hi @Boorhin, it does not seem like that dataset is available to me: I can only see the folders annual and monthly under POWER.
> 
> It is terrible, they have removed the daily average... I need to check if they moved it somewhere else or it needs to be recoded. The reader can extrapolate times?

Extrapolate? It can interpolate (sometimes only nearest), but I believe that if a value is requested outside the start or end time the reader will be discarded or not queried.

**Comment by Boorhin** [comment]
This one should do until I find a daily one again
https://opendap.larc.nasa.gov/opendap/hyrax/POWER/monthly/power_901_monthly_radiation_utc.nc.info

**Comment by knutfrode** [comment]
$ readerinfo.py https://opendap.larc.nasa.gov/opendap/hyrax/POWER/monthly/power_901_monthly_radiation_utc.nc
```
Testing /home/knutfd/software/opendrift/opendrift/readers/reader_netCDF_CF_generic.py...
===========================
Reader: https://opendap.larc.nasa.gov/opendap/hyrax/POWER/monthly/power_901_monthly_radiation_utc.nc
Projection: 
  +proj=latlong
Coverage: [degrees]
  xmin: -179.500000   xmax: 179.500000   step: 1   numx: 360
  ymin: -89.500000   ymax: 89.500000   step: 1   numy: 180
  Corners (lon, lat):
    (-179.50,  89.50)  (179.50,  89.50)
    (-179.50, -89.50)  (179.50, -89.50)
Vertical levels [m]: 
  Not specified
Available time range:
  start: 1984-01-31 00:00:00   end: 2020-12-31 00:00:00   step: 29 days, 0:00:00
    465 times (21 missing)
Variables:
  All_Sky_Surface_Shortwave_Downward_Irradiance
  All_Sky_Surface_Longwave_Downward_Irradiance
  Clear_Sky_Surface_Longwave_Downward_Irradiance
  Top-Of-Atmosphere_Shortwave_Downward_Irradiance
  Clear_Sky_Surface_Shortwave_Downward_Irradiance
  Clear_Sky_Surface_Shortwave_Direct_Horizontal_Irradiance
  Clear_Sky_Surface_Shortwave_Downward_Direct_Normal_Irradiance
===========================
```

**Comment by Boorhin** [comment]
Sorry I am trying but for some reason I don't have the same files in the test folder. I will look to see what I have installed...

**Comment by Boorhin** [comment]
I am a bit confused as the errors come from the main module and not sea-lice. 
17:19:26 DEBUG   opendrift.models.basemodel: Reader does not contain any relevant variables
Seems that there is no water velocity in this file. Could we test another file?

**Comment by gauteh** [comment]
Hi. The error you are seeing has been fixed a while ago. It was also usually only triggered when there was another error in the first place. I don't think you have the correct branch checked out. You should try to delete the local `sealice` branch if you have one, and `git fetch` the latest changes from my user: `gauteh` -> branch `sealice`: `git checkout -b sealice-gauteh gauteh/sealice`. Feel free to use other readers, the ones I used was just a suggestion.

**Comment by Boorhin** [comment]
> Hi. The error you are seeing has been fixed a while ago. It was also usually only triggered when there was another error in the first place. I don't think you have the correct branch checked out. You should try to delete the local `sealice` branch if you have one, and `git fetch` the latest changes from my user: `gauteh` -> branch `sealice`: `git checkout -b sealice-gauteh gauteh/sealice`. Feel free to use other readers, the ones I used was just a suggestion.

Thanks, I have created a virtual environment for that version. I have now another issue when importing. Seems like it is not managing to find ContinuousReader. Seems to me that everything in the __init__ of basereader points to it as it should. 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-f3c3ba1c36be> in <module>
      1 import numpy as np
      2 from opendrift.readers import reader_netCDF_CF_generic
----> 3 from opendrift.models.sealice import SeaLice
      4 from datetime import timedelta
      5 

~/DATA/Marine_plastics/PlasticsATBay/Simulations/oceano/testOD/opendrift/opendrift/models/sealice.py in <module>
     18 import numpy as np
     19 import logging; logger = logging.getLogger(__name__)
---> 20 from opendrift.models.oceandrift import Lagrangian3DArray, OceanDrift
     21 from opendrift.models.physics_methods import hour_angle, solar_elevation
     22 

~/DATA/Marine_plastics/PlasticsATBay/Simulations/oceano/testOD/opendrift/opendrift/models/oceandrift.py in <module>
     20 from scipy.interpolate import interp1d
     21 import logging; logger = logging.getLogger(__name__)
---> 22 from opendrift.models.basemodel import OpenDriftSimulation
     23 from opendrift.elements import LagrangianArray
     24 from opendrift.models.physics_methods import verticaldiffusivity_Large1994, verticaldiffusivity_Sundby1983, gls_tke

~/DATA/Marine_plastics/PlasticsATBay/Simulations/oceano/testOD/opendrift/opendrift/models/basemodel.py in <module>
     58 from opendrift.timer import Timeable
     59 from opendrift.readers.basereader import BaseReader, vector_pairs_xy, standard_names
---> 60 from opendrift.readers import reader_from_url, reader_global_landmask
     61 from opendrift.models.physics_methods import PhysicsMethods
     62 

~/DATA/Marine_plastics/PlasticsATBay/Simulations/oceano/testOD/opendrift/opendrift/readers/reader_global_landmask.py in <module>
     15 # Copyright 2020, Gaute Hope, MET Norway
     16 
---> 17 from opendrift.readers.basereader import BaseReader, ContinuousReader
     18 
     19 import warnings

ImportError: cannot import name 'ContinuousReader' from 'opendrift.readers.basereader' (/home/julien/DATA/Marine_plastics/PlasticsATBay/Simulations/oceano/testOD/opendrift/opendrift/readers/basereader.py)

```

**Comment by sebainzunza** [comment]
Hi Julien,
I'm working in my undergraduate thesis with Opendrift and I need use and modify this sealice model. In my case try to modeling larvae of the "crazy" bentonite mollusk. I would like your help to understand the configurations of your model and adapt it to my requirements. It's possible?

**Comment by sebainzunza** [comment]
HI Julien
I did not explain myself well afterwards. My question is if you can give me an example of how to call the sealice module. I need to modify it and adapt it for other types of particles. Thanks for your help. 

Sebastián

**Comment by gauteh** [comment]
@Boorhin : I updated the test with your data, but had to change the end longitude. I don't know if this makes sense. But I am merging it as it is now (if tests go through).

**Comment by Boorhin** [comment]
Thanks for that, not too sure what was wrong then.
We probably need to have a test in the gallery. I will work on it after I have finished with zarr

**Pull request merged**
