### PR TITLE
Try older commit to see docs-build duration

### PR DESCRIPTION
**Pull request by gauteh**
See if this is faster than newer version.

### CODE REVIEW

**Comment by gauteh** [comment]
> 3.5 h for approx 20 commits back but with verbosity.

**Comment by gauteh** [comment]
Ser ut til at det er interpolation eksempelet som tar so lang tid at uten noko output so går det over timeouten uten output på 40 minutt, og dermed feiler det. Då er det eit eller anna som har skjedd som gjer at det plutselig går treigare.

**Comment by gauteh** [comment]
example_interpolation takes about 1.5 hours on circleci, seems like most of the time is spent in initializing interpolator. Is the plan to remove the code entirely or should we try to fix it?

**Comment by knutfrode** [comment]
> example_interpolation takes about 1.5 hours on circleci, seems like most of the time is spent in initializing interpolator. Is the plan to remove the code entirely or should we try to fix it?

I had planned for some time to remove the two obsolete interpolators (ndimage and linearND), so that only the default and fastest option remains (linearNDFast).

The only thing would be if we would like to understand the mystery why exactly this part seems to be so much slower on CircleCI.
But I would suggest that we simply deactivate example_interpolation now, and then I can also remove the interpolators soon.

**Comment by gauteh** [comment]
Yes, i agree. Let's at least solve the circleci issue so that it doesn't
hold us back from other tasks.

ons. 4. mar. 2020, 11:03 skrev Knut-Frode Dagestad <notifications@github.com

**Comment by knutfrode** [comment]
Ok, then we could simply delete example_interpolation.
Should I make that, eventually as a separate PR? Or would you like to do it?

**Comment by gauteh** [comment]
No, feel free. Won't have the chance for a little while.

ons. 4. mar. 2020, 13:08 skrev Knut-Frode Dagestad <notifications@github.com

**Comment by knutfrode** [comment]
Deleted directly on master here: https://github.com/OpenDrift/opendrift/commit/3476d3caeae3a6c1097d786d093463265d8009a6

**Comment by knutfrode** [comment]
Then I guess we can close this PR?

**Comment by gauteh** [comment]
Yup!


ons. 4. mar. 2020, 14:04 skrev Knut-Frode Dagestad <notifications@github.com

**Pull request closed without merging**
