### PR TITLE
ChemD: unit testing - dynamic partitioning

### PR DESCRIPTION
**Pull request by manuelaghito**
first ChemicalDrift test.
5s. Too slow? 
Seems to be impossible to make a ChemicalDrift simulation less then 3s.....
ready to merge

### CODE REVIEW

**Comment by gauteh** [comment]
We have moved to the pytest framework for unit testing.

**Comment by manuelaghito** [comment]
so, what I did is the old way? Is this ok or do I need to update it? I just copied what I found in  opendrift/tests/models/

**Comment by manuelaghito** [comment]
not sure I understand the difference. Are test_models.py and test_stranding.py the old way?

**Comment by knutfrode** [comment]
Yes, those are both old school, and should also be modernized one nice day.

**Pull request merged**
