### PR TITLE
switch Matplotlib version punkrockwriters 

### PR DESCRIPTION
**Pull request by manuelaghito**
should be ready to merge.... althogh not testet for matplotlib < 3.4

### CODE REVIEW

**Comment by knutfrode** [comment]
Ser bra ut. Kan du også endre til `fastwriter=True` i `example_grid.py`?
Da kan vi se om det blir raskere enn nå på CircleCI (3min 11 sek):
https://opendrift.github.io/gallery/example_grid.html#sphx-glr-gallery-example-grid-py

**Comment by manuelaghito** [comment]
3:11 min for å kjøre hele scripten?

55s versus 96s i min maskin

-

15:05:16 INFO    opendrift.models.basemodel: Saving animation to example_grid.gif...
15:05:16 INFO    opendrift.models.basemodel: Making animated gif...
15:06:11 INFO    opendrift.models.basemodel: fastwriter=True , elapsed_time: 55.161574286874384s

15:07:25 INFO    opendrift.models.basemodel: Saving animation to example_grid_slow.gif...
15:07:25 INFO    opendrift.models.basemodel: Making animated gif...
15:09:01 INFO    opendrift.models.basemodel: fastwriter=False , elapsed_time: 96.12291857996024s

**Comment by manuelaghito** [comment]
image

**Comment by knutfrode** [comment]
Det tar veldig mye lenger tid på CircleCI enn lokalt. Blir spennende å se nå straks hvor langt tid dette eksempelet tar med fastwriter.

**Comment by manuelaghito** [comment]
image

**Comment by manuelaghito** [comment]
158s in the gallery right now..... that's the interesting number.

**Comment by knutfrode** [comment]
popcorn

**Comment by knutfrode** [comment]
Actually not much difference in this case:
fastwriter

Thus something else must be the bottleneck on CircleCI.

**Comment by knutfrode** [comment]
But the great speedup for local processing is of course a big plus anyway.

**Comment by manuelaghito** [comment]
mmmmmmm... disappointing. Is CircleCI running many processes in parallel and allocating resources as needed? Could it be that since the other are slow that this single one doesn't need to be speeded up?

**Comment by knutfrode** [comment]
Maybe it is because it is running in batch without display, and then it has to write to file anyway, somehow? I do not have enough insight in how renderers and these things work.

**Comment by manuelaghito** [comment]
I mentioned yesterday (did I?) that when I use **%matplotlib inline** in ipython then there is no big advantage.... only when I use **%matplotlib qt** then I see the big advantage of 20-40%. I tried now again with %matplotlib inline, and then I get only 97s versus 105s..... this is more similar to CircleCI.. so maybe there is a common reason

**Comment by manuelaghito** [comment]
when I run directy from terminal with python example_grid.py I get 87s/155s, much slower than in Spyder with **%matplotlib qt** this was also surprising.....

**Pull request merged**
