### PR TITLE
add shyfem reader

### PR DESCRIPTION
**Pull request by gauteh**

### CODE REVIEW

**Comment by knutfrode** [comment]
Ready to merge?

**Comment by gauteh** [comment]
No, not quite yet.

man. 26. apr. 2021, 08:40 skrev Knut-Frode Dagestad <
***@***.***>:

**Comment by gauteh** [comment]
I think this should be ready now, @Manuel Aghito ***@***.***> do you
think the shyfem-reader is functional and not incorrect as it is?

man. 26. apr. 2021 kl. 09:01 skrev Gaute Hope ***@***.***>:

**Comment by gauteh** [comment]
@manuelaghito : can you check if the latest edition makes sense. This uses the middle of layer rather than the bottom.

**Comment by manuelaghito** [comment]
> @manuelaghito : can you check if the latest edition makes sense. This uses the middle of layer rather than the bottom.

I guess you are right, since level description is "bottom of vertical layers" this should correct, I think we can merge this

**Pull request merged**
