### PR TITLE
oil-budget-example

### PR DESCRIPTION
**Pull request by gauteh**

### CODE REVIEW

**Comment by knutfrode** [comment]
Good with some cleaning. However, the oil budget figure does still not show up here:
https://opendrift.github.io/gallery/example_oil_budget.html
Is something missing in the example script?

**Comment by gauteh** [comment]
It won't show on the main site before we merge to master, I got it showing locally. I think the issue was a plt.close('all') in animation(). However, there are still some plots missing. Also it seems that multiple animations per example does not work (probably something with the static counter).

**Comment by knutfrode** [comment]
Of, course, it was not merged yet!
But now oil budget shows, very good.
On the other hand, the animation is now not there anymore :-)

**Comment by gauteh** [comment]
Oh, that's not good... :/

ons. 18. mar. 2020 kl. 10:16 skrev Knut-Frode Dagestad <
notifications@github.com>:

**Comment by gauteh** [comment]
Weird, the animation is generated locally.

ons. 18. mar. 2020 kl. 10:18 skrev Gaute Hope <gauteh@met.no>:

**Pull request merged**
