### PR TITLE
Speeding up allocation of self.history in import_file

### PR DESCRIPTION
**Pull request by manuelaghito**
for some reason numpy.ma.array allocation is extremely slow when mask=True is passed

### CODE REVIEW

**Comment by knutfrode** [comment]
Ah, yes!
In fact, we should aim to remove masked arrays completely from OpenDrift.

**Comment by manuelaghito** [comment]
now it should be ok, hopefully :-) was very eager when I found the problem :-)
image

**Comment by manuelaghito** [comment]
by the way if we don't need all values to be masked then we can remove the line **self.history[:] = np.ma.masked** then it is even faster. But at least like it is proposed now the initially allocated **self.history** should be exactly the same as before, as far as I can see, all zeros, all masked

**Comment by manuelaghito** [comment]
just notied that I didn't pull the latest master with the recent commit https://github.com/OpenDrift/opendrift/commit/1d1df93aad71d111f313af34f763001e3bf7ef86

**Comment by manuelaghito** [comment]
I am not sure what is going on here, I just close this and make a new one

**Pull request merged**
